// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLSX37aIwj8wu8LhEfRo1nsXmnkTarGys',
    appId: '1:643482796193:web:f719be8ad2680cd35f30e0',
    messagingSenderId: '643482796193',
    projectId: 'black-pepper-2',
    authDomain: 'black-pepper-2.firebaseapp.com',
    storageBucket: 'black-pepper-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfgyax4kWMiC5x--3mAiKBzjVadwRPQc',
    appId: '1:643482796193:android:484f46777b4eed4f5f30e0',
    messagingSenderId: '643482796193',
    projectId: 'black-pepper-2',
    storageBucket: 'black-pepper-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUnJaLiLIVx5KGKtonLGMZ10ff61P1e8',
    appId: '1:643482796193:ios:155149147c8094c35f30e0',
    messagingSenderId: '643482796193',
    projectId: 'black-pepper-2',
    storageBucket: 'black-pepper-2.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGUnJaLiLIVx5KGKtonLGMZ10ff61P1e8',
    appId: '1:643482796193:ios:155149147c8094c35f30e0',
    messagingSenderId: '643482796193',
    projectId: 'black-pepper-2',
    storageBucket: 'black-pepper-2.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLSX37aIwj8wu8LhEfRo1nsXmnkTarGys',
    appId: '1:643482796193:web:388f521ef10fa29b5f30e0',
    messagingSenderId: '643482796193',
    projectId: 'black-pepper-2',
    authDomain: 'black-pepper-2.firebaseapp.com',
    storageBucket: 'black-pepper-2.firebasestorage.app',
  );
}
